name: Terraform Dev Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # Get GitHub OIDC token and display only its claims
      - name: Debug OIDC Claims
        working-directory: .
        run: |
          echo "Getting GitHub OIDC token..."

          RESPONSE=$(curl -sSf \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

          TOKEN=$(echo "$RESPONSE" | jq -r '.value')

          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2)

          # Add base64 padding
          PADDING=$((4 - ${#PAYLOAD} % 4))
          if [ "$PADDING" -lt 4 ]; then
            PAYLOAD="${PAYLOAD}$(printf '=%.0s' $(seq 1 $PADDING))"
          fi

          echo "$PAYLOAD" | base64 -d | jq '{
            sub: .sub,
            aud: .aud,
            repository: .repository,
            ref: .ref
          }'

      - name: AWS Access using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881819579:role/github-oidc-vcube
          role-session-name: github-actions
          aws-region: ap-south-1
          retry-max-attempts: 1

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars


  apply:
    runs-on: ubuntu-latest

    needs: plan

    defaults:
      run:
        working-directory: dev

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: AWS Access using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::713881819579:role/github-oidc-vcube
          role-session-name: github-actions
          aws-region: ap-south-1
          retry-max-attempts: 1

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=dev.tfvars
